# Config file for mosquitto
# Regular MQTT over TCP (default port 1883)
listener 1883
protocol mqtt

# MQTT over WebSockets (often port 9001)
listener 9001
protocol websockets

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# uncomment on first launch
#allow_anonymous true
# only comment above _OR_ below
password_file /mosquitto/config/pwfile

#log_type all
