################################################################################
# Home Assistant Configuration
################################################################################

# Nothing to see here. Move along.
homeassistant:
  packages: !include_dir_named packages

# need to change this if I use/create automations
#automation: !include automations.yaml

# i really need this I guess, look up other stuff
default_config:

recorder:
  purge_keep_days: 90
  db_url: !env_var POSTGRES_CONNECTION

prometheus:
  namespace: hass

# Example configuration.yaml entry
http:
##  server_host: 0.0.0.0

api:

websocket_api:

# https://www.home-assistant.io/integrations/logger/
logger:
  # some options are: `info`, `debug`, `warning`, `error`, `criticial`, `fatal`
  default: warning

# https://www.home-assistant.io/integrations/system_log/
system_log:
  max_entries: 100
  fire_event: true

# enable the mobile_app
mobile_app:

# https://www.home-assistant.io/integrations/homekit/
#homekit:
#  filter:
#    include_domains:
#      - light

# this might be useful
wake_on_lan:

my:
