# Enable the Zigbee2MQTT frontend
frontend:
  enabled: true
  # Optional, default 8080
  port: 8080
  # Experimental new frontend, see: https://github.com/Koenkk/zigbee2mqtt/releases/tag/2.4.0
  package: zigbee2mqtt-windfront

serial:
  # https://github.com/Koenkk/zigbee2mqtt/discussions/24364
  adapter: zstack # <-- Add this line
  # Could be either USB port (/dev/ttyUSB0), network Zigbee adapters (tcp://192.168.1.1:6638) or mDNS adapter (mdns://my-adapter).
  port: /dev/ttyUSB0

homeassistant:
  enabled: true
  # Optional: Home Assistant discovery topic (default: shown below)
  discovery_topic: 'homeassistant'
  # Optional: Home Assistant status topic (default: shown below)
  # Note: in addition to the `status_topic`, 'homeassistant/status' will also be used
  status_topic: 'homeassistant/status'
  # Optional: Experimental support for Home Assistant event entities, may break in the future (default: shown below) when enabled:
  # - An `event` entity will be discovered for each 'action'.
  # - The `event_type` attribute will contain the action itself, additional attributes like `button` will have further information.
  experimental_event_entities: true
  # Optional: Home Assistant legacy action sensor (default: `false`), when enabled:
  # - Zigbee2MQTT will send an empty 'action' after one has been send
  # - A 'sensor_action' will be discovered
  legacy_action_sensor: true

# Let Zigbee2MQTT generate a new network key on first start
# https://github.com/Koenkk/zigbee2mqtt/issues/16188
# most of below is from a reset: https://github.com/Koenkk/zigbee2mqtt/blob/0cbbf400401e7f2ed0a139178f0097ece66c6fd3/lib/controller.ts#L111-L118
advanced:
  # Let Zigbee2MQTT generate a network key on first start
  network_key: GENERATE
  # Let Zigbee2MQTT generate a pan_id on first start
  pan_id: GENERATE
  # Let Zigbee2MQTT generate a ext_pan_id on first start
  ext_pan_id: GENERATE
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  # https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-payload
  # Whether to use legacy mode for the availability message payload (default: true)
  # true = online/offline
  # false = {"state":"online"} / {"state":"offline"}
  legacy_availability_payload: false
  # https://www.zigbee2mqtt.io/guide/configuration/mqtt.html#mqtt-behaviour
  # Optional: state caching, MQTT message payload will contain all attributes, not only changed ones.
  # Has to be true when integrating via Home Assistant (default: true)
  cache_state: true
  # Optional: persist cached state, only used when cache_state: true (default: true)
  cache_state_persistent: true
  # Optional: send cached state on startup, only used when cache_state_persistent: true (default: true)
  cache_state_send_on_startup: true
  # Optional: Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message
  # possible values are: disable (default), ISO_8601, ISO_8601_local, epoch (default: disable)
  last_seen: 'ISO_8601_local'
  # Optional: Add an elapsed attribute to MQTT messages, contains milliseconds since the previous msg (default: false)
  elapsed: true

# https://github.com/Koenkk/zigbee2mqtt.io/blob/dev/docs/guide/configuration/device-availability.md
# Optional: Availability feature
availability:
  # Enable the feature (default: false)
  enabled: true

# https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html
device_options:
  legacy: false
  state_action: true

# https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html#extract-config-to-separate-files
devices: devices.yaml

devices:
  '0x00158d00090d9eaa':
    friendly_name: Magic Cube
    description: This is an Aqara Magic Cube

# does not seem to work though
# https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html#extract-config-to-separate-files
# Define the files which contains the configs
#devices: 'devices.yaml'
